= OpenShift Virtualization API コンポーネントの概要
:navtitle: API コンポーネントの概要

NOTE: テスト済みの OpenShift バージョン: v4.19, v4.20

IMPORTANT: このリファレンスガイドでは、OpenShift Virtualization API コンポーネントの概要を説明し、これらのコンポーネントおよびプラットフォーム全体のアーキテクチャに関する最も重要な内容を扱います。
これは包括的な API リファレンスではありません。新しい API 開発者向けのクイックスタートガイドとして意図されています。

初心者の方や他の仮想化プラットフォームから移行される方のために補足すると、OpenShift Virtualization はアップストリームプロジェクトである https://kubevirt.io[KubeVirt,window=_blank] をベースにしており、その KubeVirt は Kubernetes をベースとする OpenShift の上に構築されています。
OpenShift (およびその基盤である Kubernetes) のアーキテクチャは、json または yaml 形式で表現できる API オブジェクトによって定義される宣言型の設計を採用しています。
OpenShift Virtualization は、この宣言型 API を仮想化固有のオブジェクトで拡張しています。初心者にとって、これらの各オブジェクトの役割や相互の関係は混乱を招く可能性があります。

本ガイドでは、一般的なアーキテクチャガイドと API ガイドを統合し、各 API コンポーネント（オブジェクトやリソースとも呼ばれます）の役割とコンポーネント間の関係を明確にするとともに、各コンポーネントの API の詳細にも触れます。

そのため、完全な yaml の例やスキーマは避け、特定オブジェクトの断片や最も重要なフィールドのサブセット（`ドット.表記`）を優先しています。
詳細な例については https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/virtualization/index[OpenShift Virtualization,window=_blank] および https://kubevirt.io/user-guide/[KubeVirt,window=_blank] のドキュメントを参照し、完全な API スキーマについては https://kubevirt.io/api-reference/main/index.html[KubeVirt API reference,window=_blank] を参照してください。

扱われる内容は以下の通りです。

* <<virtualization_apis,仮想化 API>>
** <<virtual_machines,VirtualMachines>>
** <<virtual_machine_instances,VirtualMachineInstances>>
** <<instance_types,インスタンスタイプ>>
** <<vm_cluster_instance_types,VirtualMachineClusterInstanceTypes>>
** <<vm_instance_types,VirtualMachineInstanceTypes>>
** <<virtual_machine_preferences,VirtualMachinePreferences および VirtualMachineClusterPreferences>>
** <<preferred_cpu_topology,PreferredCPUTopology>>
** <<vcpu_spread_options,vCPU SpreadOptions>>
* <<networking_apis,ネットワーキング API>>
** <<networks,Networks>>
** <<interfaces,Interfaces>>
** <<default_network,デフォルトネットワーク>>
** <<multus_cni_plugin,Multus CNI プラグイン>>
** <<nmstate_operator,NMState Operator>>
* <<storage_apis,ストレージ API>>
** <<persistent_volumes,PersistentVolumes>>
** <<persistent_volume_claims,PersistentVolumeClaims>>
** <<volume_snapshots,VolumeSnapshots>>
** <<data_volumes,DataVolumes>>
** <<data_sources,DataSources>>
** <<storage_classes,StorageClasses>>
** <<virtual_machine_snapshots,VirtualMachineSnapshots>>
** <<virtual_machine_restores,VirtualMachineRestores>>
* <<clone_api,クローン API>>
** <<virtual_machine_clones,VirtualMachineClones>>
** <<mutating_vm_clones,クローン VM の変更>>
** <<patching_vm_clones,クローン VM のパッチ適用>>
** <<vm_cloning_strategies,クローニング戦略と StorageProfiles>>
* <<export_api,エクスポート API>>
** <<virtual_machine_exports,VirtualMachineExports>>

== 仮想化 API [[virtualization_apis]]

=== VirtualMachines [[virtual_machines]]
VirtualMachine は API オブジェクト（厳密には Kubernetes カスタムリソース）であり、OpenShift Virtualization において実行されていない VirtualMachine を表現します。

VirtualMachine には VirtualMachineInstance（次セクションで解説）のテンプレートが含まれており、Status の一部として実行状態を反映します。

VirtualMachine には `spec` 内に VM の詳細を定義する多数のフィールドが含まれます。その一部を以下に示します。

* `instanceType` - VirtualMachine に使用する <<instance_types,インスタンスタイプ>> 名（RAM と CPU の割り当て量でサイズ指定されます）。
* `volumes` - 仮想ディスクとして VM に接続されるボリュームのリスト。このフィールドは https://kubevirt.io/user-guide/storage/disks_and_volumes/#volumes[複数のボリュームタイプ,window=_blank] をサポートしていますが、`dataVolume` と `persistentVolumeClaims` が最も一般的です。
** `dataVolume` - この VM 用にプロビジョニングされる <<data_volumes,DataVolume(s)>> の名前を示します。作成される DataVolume(s) は `dataVolumeTemplates` セクション内で定義されます。
** `persistentVolumeClaim` - <<persistent_volume_claim,PersistentVolumeClaim>> をディスクとして VM に接続します。
* `networks` - VM に接続されたインターフェースにバインドされる <<networks,networks>> のリスト。空のフィールドの場合、デフォルトでデフォルトの Pod/VM ネットワークが使用されます。
* `interfaces` - VM に接続されたネットワーク <<interfaces,interfaces>> のリスト。インターフェースは仮想化された NIC と考えることができ、Pod/VM を特定のネットワークに接続するために使用されます。
* `dataVolumeTemplates` - 作成される <<data_volumes,DataVolume マニフェスト>> のリスト。ここにリストされている DataVolume は、`volumes` セクションで名前によって参照される必要があります。

VirtualMachine の実行状態は、通常 `spec.runStrategy` フィールドを介して管理され、以下の値を指定できます。

* **Always** - 電源オン状態がデフォルトとなり、何らかの理由で（手動シャットダウンやクラッシュなどを問わず）停止した場合に VM が再起動します。
* **RerunOnFailure** - Always と同様ですが、VM がクラッシュした場合のみ再起動し、正常にシャットダウンされた場合（スケジュールやゲスト内からの手動シャットダウンなど）は再起動しません。
* **Once** - VM は一度だけ起動され、クラッシュしたか手動でシャットダウンされたかに関わらず、二度と起動されません。
* **Manual** - 実行状態は自動管理されず、VM のステータスサブサブリソースに対して POST された電源コマンドにのみ応答します。
* **Halted** - `spec.runStrategy` が変更されるか、VM に対して `start` コマンドが発行されるまで VM をシャットダウン状態にします（このトピックについては後述）。

NOTE: `spec.running` フィールドは非推奨となっており、`spec.runStrategy` フィールドと相互排他です。

`virtctl` コマンドを使用して、VirtualMachine のステータスサブリソースに影響を与える `start`、`stop`、`restart` コマンドを発行することもできます。これは KubeVirt が VM の現在の状態を反映するために使用する `../status` API エンドポイントです。

これらの各コマンドが発行された場合、その発行先である VirtualMachine の `runStrategy` に影響を与える可能性があります。各ケースは以下の通りです。

* **start** - VM を起動し、`Halted` 実行戦略を `Always` に戻します。これは `RerunOnFailure` や `Manual` 実行戦略には影響しません。
* **restart** - 実行中の VM を再起動しますが、実行戦略には影響しません。これは `Halted` VM に対しては何もしません。
* **stop** - VM を停止し、`Always` 実行戦略を `Halted` に戻します。これは `RerunOnFailure` や `Manual` 実行戦略には影響しません。

API レベルでは、`Manual` 実行戦略を持つ VM に対して電源コマンドが発行されると、以下のように `stateChangeRequests[]` リストが VirtualMachine ステータスサブリソースに追加されます。

[source,yaml]
----
status:
  stateChangeRequests:
  - action: <Stop|Start> <1>
    uid: <uid-of-the-virtual-machine-instance> <2>
----
<1> 要求されているアクション。以下のいずれかの文字列値 (`Stop`, `Start`)。
<2> アクションを実行する対象の VirtualMachineInstance (VirtualMachine ではない) のオプションの UID。VM が起動すると VMI が作成されるため、`Start` コマンドでは不要です。

VirtualMachine に対して API アクションを実行する場合、VM `status` に現在の実行状態を反映するいくつかの異なるフィールドがあります。

* **status.printableStatus** - VM の電源状態を確認するための最もシンプルなフィールドで、`Running` (起動済み/準備完了)、`Starting` (処理中/起動中)、`Stopped` 状態を反映します。
* **status.runStrategy** - アクティブな実行戦略を反映します。`spec.runStrategy` フィールドと同様の `Always`、`RerunOnFailure`、`Once`、`Manual`、`Halted` といった値を反映します。
* **status.conditions["type": "Ready"]** - `conditions` は以下のフィールドを含むオブジェクトのリストを受け入れます: `type` - 文字列値（この場合は `Ready`）、`status` - ブール値、`Reason` および `Message` - それぞれオプションの理由コードと説明。
「まだ準備ができていない」状態の例は以下の通りです。

[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-status-example
spec:
  ...
status:
  conditions:
    - lastProbeTime: "2025-11-10T15:00:46Z"
      lastTransitionTime: "2025-11-10T15:00:46Z"
      message: Guest VM is not reported as running
      reason: GuestNotRunning
      status: "False"
      type: Ready
----

=== VirtualMachineInstances [[virtual_machine_instances]]

VirtualMachineInstance (VMI) は、OpenShift Virtualization における実行中の VM の現在の設定を反映します。

内部的には、VirtualMachineInstances は Kubernetes Pod に紐付いています。Pod は QEMU / KVM ハイパーバイザーを格納して実行し、VM ディスクイメージ（ルートディスクおよび追加ディスク）を PersistentVolumeClaim としてマウントするコンテナ（のグループ）です。

VirtualMachine との関係において、VirtualMachineInstance は VM が起動された際、VM `template`、具体的には `spec.template` の yaml (json) 定義から生成されます。

VM 起動時に VMI が作成されるのと同様に、VM が停止されて VMI が削除されると、その逆のプロセスが発生します。
VMI が削除されても、基盤となるストレージボリューム（DataVolumes、PVC、およびその下の PV）は影響を受けず、そのまま保持されます。

VM が再度起動されると、VM の yaml/json で定義されたテンプレートから新しい VMI が作成され、同じボリュームがその新しい VMI に接続されます。

=== インスタンスタイプ [[instance_types]]

他のクラウドプラットフォームと同様に、OpenShift Virtualization では CPU およびメモリリソースは名前付きのインスタンスタイプに基づいて決定されます。
これらのインスタンスタイプは、目的や機能セットに応じて文字でグループ化され、世代によって番号付けされています（例: u1）。
各グループには、リソース割り当てによってスケールされた T シャツサイズ（small, medium, large, xlarge, 2xlarge など）のインスタンスタイプの選択が含まれており、サイズはインスタンスの文字と番号の後に続きます（例: u1.xlarge）。
各インスタンスグループのスケーリング比率は、想定される用途（メモリ集約型 vs CPU 集約型）によって異なります。

OpenShift Virtualization では、以下のデフォルトインスタンスタイプが利用可能です。

* **Network (N)** - ネットワーク集約型のワークロード用。DPDK 対応ノードが必要。CPU/RAM 比率は 1:2。
* **Overcommitted (O)** - 完全な RAM 消費が期待されない、または不要な場合に使用。ホストメモリのオーバープロビジョニングを許可。CPU/RAM 比率は 1:4。
* **Compute Exclusive (CX)** - CPU 集約型のワークロード用。専用の CPU コア/スレッドで実行。CPU/RAM 比率は 1:2。
* **General Purpose (U)** - 「ユニバーサル」または一般的なワークロード用。共有ホスト CPU コア/スレッドで実行。CPU/RAM 比率は 1:4。
* **Memory Intensive (M)** - メモリ集約型のワークロード用。ホストメモリのオーバープロビジョニングを許可しない。CPU/RAM 比率は 1:8。

上記の各インスタンスタイプのすべてのサイズは、クラスターレベルで VirtualMachineClusterInstanceType として定義されています。

=== VirtualMachineClusterInstanceTypes [[vm_cluster_instance_types]]

VirtualMachineClusterInstanceType は、クラスタースコープでインスタンスタイプを定義します。前述の通り、これらは OpenShift Virtualization で新しい VM をプロビジョニングする際にデフォルトのインスタンスタイプを選択できるようにするために使用されます。

VirtualMachineClusterInstanceTypes は以下のフィールド仕様をサポートしています（トップレベルのフィールドの一部は省略）。

* **annotations** - このタイプのインスタンスに適用するオプションの注釈セット
* **cpu** (必須) - このインスタンスタイプの CPU 関連の設定を定義します
** **dedicatedCPUPlacement** - VM の vCPU をホストノードの物理 CPU コア/スレッドに分離するかどうか。デフォルトは `false`。
** **guest** (必須) - ゲストに公開する vCPU の数。デフォルトは `0`。
** **isolateEmulatorThread** - VMI のエミュレーター・スレッドを追加の専用物理 CPU コア/スレッドに配置するかどうか。デフォルトは `false`。
** **maxSockets** - ホットプラグ可能なソケットの最大数を指定します。
** **model** - VMI 内で使用する CPU モデルを指定します。デフォルトは `host-model`。
** **numa** - ホストの NUMA 設定を構成するために使用されます
*** **guestMappingPassthrough** - 仮想 NUMA ノード上のメモリと CPU がホスト上の別の NUMA ノードにまたがらないことを保証するゲストトポロジーを作成します。デフォルトは `{}`。
** **realtime** - virt-launcher Pod に対して低レイテンシー向けに VMI をチューニングするよう指示します。リアルタイムワークロード向け（オプション）。
*** **mask** - リアルタイムに使用される vCPU を定義するマスク式。`"0-3,^1"`, `"1,2,3"`, `"1-2"` などの基盤となる libvirt 式フォーマットと一致します。
* **gpu** - インスタンスタイプに関連付けられた GPU デバイスを定義します
** **deviceName** - 文字列値。デフォルトは `""`。
** **name** (必須) - デバイスプラグインに関連付けられた GPU デバイスの名前。デフォルトは `""`。
** **tag** - 設定ドライブを介してゲストに公開する指定のタグおよび仮想ネットワークインターフェースアドレス。
** **virtualGPUOptions** - vGPU 用のオプションフィールド
*** **display** - vGPU の表示オプション
**** **enabled** - vGPU をバックアップするディスプレイアダプターを有効にするかどうか。デフォルトは `true`。
**** **ramFB** - ゲスト OS が実際の GPU ドライバーをロードするまでブートフレームバッファを有効にするかどうか。
***** **enabled** - デフォルトは `true`。
* **hostDevices** - オプションで、インスタンスタイプとともに公開するデバイスを定義します
** **deviceName** (必須) - ホストデバイスのリソース名。デフォルトは `""`。
** **name** (必須) - デフォルトは `""`。
** **tag** - 設定ドライブを介してゲストに公開する指定のタグおよび仮想インターフェースアドレス
* **memory** (必須) - このインスタンスタイプのメモリ関連の設定を定義します
** **guest** (必須) - ゲスト OS に公開するメモリの単位付き文字列値（`"4096Mi"` や `"6Gi"` など）。
** **hugepages** - 通常のメモリの代わりに VMI 用のヒュージページを使用できるようにします
*** **pageSize** - ヒュージページサイズを指定します。amd64 アーキテクチャの有効なサイズは `1Gi` および `2Mi` です。
** **maxGuest** - ゲスト内部で表示される最大メモリ量を指定します。`maxGuest` と `guest` の差分が、ホットプラグ可能なメモリ量となります。
** **overcommitPercent** - オーバーコミットされるゲストメモリの割合、または virt-launcher Pod で必要とされるメモリの削減率。デフォルトは `0`。
* **nodeSelector** - このインスタンスタイプで希望するノードをスケジュールするために使用される Kubernetes セレクターラベル
** **schedulerName** - インスタンスタイプ用のカスタム Kubernetes スケジューラーを指定します。空の場合、デフォルトの K8s スケジューラーが使用されます。

=== VirtualMachineInstanceTypes [[vm_instance_types]]

VirtualMachineInstanceType は VirtualMachineClusterInstanceType と同様ですが、クラスタースコープではなくネームスペーススコープです。これは、通常の（クラスター管理者ではない）ユーザーが独自のカスタムインスタンスタイプを定義し、アクセス権のあるプロジェクト/ネームスペース内でのみ利用できるようにする場合に便利です。

IMPORTANT: `spec.instancetype` フィールドは OpenShift Virtualization Web コンソールで必須であり、`spec.template.spec.domain.cpu` または `spec.template.spec.domain.memory` が設定されている場合は設定できないため、CPU とメモリの設定を手動で指定するのではなく、VirtualMachine に使用するインスタンスタイプを選択または定義する必要があります。これは、インスタンスタイプが VM 起動時に VirtualMachineInstance の後者 2 つのフィールドを補完するために使用されるためです。

=== VirtualMachinePreferences および VirtualMachineClusterPreferences [[virtual_machine_preferences]]

VirtualMachineInstanceTypes と同様に、VirtualMachinePreferences はインスタンスタイプオブジェクトではカバーされない残りのマシン固有の設定を保存するために使用されます。
ただし、これらの設定は単なる「好み（preference）」であり、VirtualMachine オブジェクトを直接変更することでオーバーライドできます。

インスタンスタイプと同様に、同じ `spec` を受け入れる VirtualMachineClusterPreferences も存在しますが、これらはクラスタースコープに適用されます。

OpenShift Virtualization では、VirtualMachineClusterPreferences は OS ごとに最適化された設定を保存するために使用され、OS に従って名前が付けられています（`fedora`、`rhel10`、`win11` など）。
たとえば、一部の OS イメージは UEFI ファームウェアではなく従来の BIOS を使用して起動するように構築されているため、特定の OS を実行する VM が適切に起動できるように VirtualMachineClusterPreference で設定されます。

以下は、SecureBoot を有効にした EFI ファームウェアを使用して起動するように設定された VirtualMachineClusterPreference の例です。

[source,yaml]
----
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  name: rhel10-custom
spec:
  firmware:
    preferredUseEfi: true
    preferredUseSecureBoot: true
----

NOTE: VirtualMachinePreference spec で VM に BIOS ファームウェアを指定するには、`preferredUseEfi` の代わりに `spec.firmware.preferredUseBios` を使用してください。SecureBoot は UEFI の排他的機能であることに留意してください。

=== PreferredCPUTopology [[preferred_cpu_topology]]

VirtualMachinePreferences のもう 1 つの便利な機能は、VirtualMachineInstanceType で定義された vCPU 数がゲスト OS にどのように提示されるか（CPU トポロジー）を調整できることです。
これは、CPU ソケット、コア、およびスレッドの数が vCPU 数全体にどのように分割されるかを制御するもので、ゲスト内部から VM が CPU トポロジーをどのように「見る」かのみに影響し、ホストの CPU ソケット、コア、またはスレッドの割り当てとは無関係です。

preferredCPUTopology にはいくつかの異なる設定があります。

* **sockets** (デフォルト) - vCPU はゲスト OS にソケットとして提示されます
* **cores** - vCPU はゲスト OS にコアとして提示されます
* **threads** - vCPU はゲスト OS にスレッドとして提示されます
* **spread** - vCPU はデフォルトでソケットとコアに分散されますが、`spreadOptions` を設定することでチューニング可能です（下記参照）。
* **any** - vCPU はソケットとしてゲスト OS に割り当てられ、vCPU の割り当てはすべてこの設定の要件となります（関連するインスタンスタイプなしで優先順位を定義するために使用されます）

=== vCPU SpreadOptions [[vcpu_spread_options]]

preferredCPUTopology が `spread` に設定されている場合はいつでも、`spreadOptions` を使用して vCPU をコア、スレッド、ソケット全体にどのように提示するかを調整できます。

`spreadOptions` には 2 つのフィールドが含まれます。

* **across** - vCPU をソケット、コア、スレッド全体にどのように分散するかを定義するために使用されます
* **ratio** (デフォルトは `2`) - ソケットあたりのコア数（以下 `N` と呼びます）

`across` の値は以下の通りです。

* **SocketsCores** (デフォルト) - vCPU は、1 ソケットあたり `N` コアの比率でソケットとコアに分散されます。
* **SocketsCoresThreads** - vCPU は、1 ソケットあたり `N` コア、1 コアあたり 2 スレッドの比率でソケット、コア、スレッドに分散されます。
* **CoresThreads** (2 つ以上の vCPU が必要) - vCPU はコアとスレッドに分散されますが、1 コアあたり 2 スレッドという比率が「強制」されます。

カスタム `preferredCPUTopology` を使用した VirtualMachinePreference の例を以下に示します。

[source,yaml]
----
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: cpu-topology-example
spec:
  cpu:
    preferredCPUTopology: spread
    spreadOptions:
      across: SocketsCoresThreads
      ratio: 6
----

== ネットワーキング API [[networking_apis]]

このセクションでは、VirtualMachine および VirtualMachineInstances 内にあるネットワーク関連のサブ API に焦点を当てますが、Multus CNI や NMState Operator など、VM/VMI 外部のネットワーキングコンポーネントについても触れます。

VirtualMachine レベルでのネットワーキングの構成は、2 つの部分（相互に依存しているため両方が必須）に分かれています。以下で解説する `networks` と `interfaces` です。

=== Networks [[networks]]

VirtualMachine では、ネットワークは Pod スペック (`spec.template.spec`) の `networks[]` フィールドで設定されます。複数のネットワークをリストできます（`[]` で示される通り）が、各ネットワークの名前は一意である必要があります（特定の `kind` のすべての Kubernetes リソース名と同様）。ネットワークには、VirtualMachine マニフェスト内で定義された同じ名前のインターフェース（後述）が必要です。

各ネットワークは、`spec.template.spec.networks[]` に 2 つの異なるタイプのいずれかとして宣言する必要があります。

* *pod* - デフォルトの Kubernetes ネットワーク。プライマリネットワークとしてのみ使用。
* *multus* - Multus CNI プラグインは追加ネットワークの使用を可能にします。プライマリネットワークとしても使用可能。

=== Interfaces [[interfaces]]

VirtualMachine において、インターフェースは VM に接続された仮想ネットワークインターフェースカード（NIC）を表します。
インターフェースはホスト Pod 内で実行されているゲスト VM に仮想化アダプターとして提示され、`virtio` をサポートしないゲスト（Windows など）に対しては、OpenShift Virtualization によって異なるモデル（完全仮想化 NIC）がサポートされます。

インターフェースは VirtualMachine オブジェクト内の `spec.domain.devices.interfaces[]` で定義され、機能させるためには関連付けられた `network` が必要です。

インターフェース内でサポートされているフィールドの網羅的ではないリストを以下に示します（必須なのは 2 つのフィールドのみであることに注意してください）。

* **name** (必須) - VirtualMachine の `spec.template.spec.networks[]` 内で定義された `network` と一致する名前。
* (必須) - 以下の中核バインディングまたはネストされたネットワーク `binding` プラグインの名前:
** **bridge** - Linux ブリッジを使用して名前付きネットワークに接続します
** **sriov** - パススルー SR-IOV VF（`vfio` を使用）を使用して接続します
** **masquerade** - 送信および受信の両方で NAT または IP マスカレード（`nftables` ルールを使用）を使用してネットワークに接続します
** **binding** - 追加の（非中核）ネットワークバインディングプラグインの使用を可能にします
*** **name** - サポートされているネットワークバインディングプラグインの名前。具体的には以下の「いずれか」の値:
**** **l2bridge** - VM `interface` と目的の `network` との間に直接レイヤー 2 接続を作成します
**** **passt** (テクノロジープレビュー) - Plug a Simple Socket Transport。Pod ネットワークとの統合性が向上し、結果として OpenShift ネットワークエコシステムとの統合が向上するユーザースペースソリューションです。
* **model** - サポートされている以下のアダプターのいずれかの名前 (10/100 アダプターは省略)
** **e1000** - Intel 82545EM PCI ギガビットイーサネットアダプターを仮想化します
** **e1000e** - Intel 82574 PCI-E ギガビットイーサネットアダプターを仮想化します
** **virtio** - ディスクおよびネットワークデバイス用の仮想化標準であり、Linux ゲスト（推奨）でのパフォーマンスを向上させます。
* **macAddress** - ゲスト内部から見える MAC アドレス
* *ports* - VM ゲストに転送するポートのリスト
** **name** - 特定ポートのフレンドリーネーム
** **port** - ポート番号（`0` から `65535` までの整数値）
* **pciAddress** - `0000:81:00.1` のようにゲスト内でアダプターに割り当てる PCI アドレス

VM を定義する際の具体的な使用例については、ネットワーキングのセクションを参照してください。

=== デフォルトネットワーク [[default_network]]

これは（名前が示す通り）OpenShift および Kubernetes の Pod で使用されるデフォルトのネットワークです。
以下の例のように、空の `pod: {}` ネットワークと空の `masquerade: {}` インターフェースを定義するだけで選択されます。

[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: default-network-example
  namespace: my-namespace
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
          - name: default <1>
            masquerade: {} <2>
      networks:
      - name: default <1>
        pod: {} <3>
----
<1> `domain.devices.interfaces` (`spec.template.spec` の下) で定義されたネットワーク名は、VM テンプレートスペック内の `networks` 下にある目的のネットワーク名と一致する必要があります。
<2> デフォルトネットワークは IP マスカレード（NAT）を使用して NIC を基盤ネットワークに接続します
<3> これにより、基盤ネットワークとして Kubernetes Pod ネットワークが選択されます

デフォルトネットワークを使用する利点は以下の通りです。

* OpenShift にネイティブであり、ネイティブな方法で設定できる
* 送信や、同じネームスペースおよび同じノード上の Pod 間通信に追加の設定が不要
* ロードバランシングと（内部的な）IP アドレスの安定性のために Kubernetes サービスを使用できる
* サポートされているプラットフォーム上で OpenShift Route や LoadBalancer サービスを使用して外部に公開できる

デフォルトネットワークの欠点はわずかですが、注目に値します。

* VM が使用するマスカレード IP アドレスは、外部からルーティングできない
* 外部ネットワークには接続できず、同じプロジェクト/ネームスペース内のサービスを使用しない限り、他のノード上の Pod にも接続できない
* VLAN をサポートしていない
* 一部のプラットフォーム (AWS) では、LoadBalancer サービスが混合モード（TCP と UDP の同時）のポートフォワーディングをサポートしていない

=== Multus CNI プラグイン [[multus_cni_plugin]]

Multus は、コンテナネットワークインターフェース（CNI）の「メタプラグイン」です。CNI では単一のプラグインしかデプロイできませんが、
Multus は仲介役として機能し、複数の CNI プラグインを同時に、または相互に入れ替えて使用できるようにします。

<<networks,Networks>> セクションで述べたように、Multus を使用すると、サポートされているさまざまな CNI プラグインを使用して追加のネットワークを定義できます。

これらのプラグインは以下の通りです。

* **bridge** - 同じノードで実行されている Pod 間のネットワークスイッチとして機能し、外部ネットワークへの接続用にホストネットワークインターフェースにリンクできます。
* **host-device** - ホストネットワークインターフェースを Pod ネットワークネームスペースに「移動」させ、インターフェースをルートネットワークネームスペースから消滅させます。
* **ipvlan** - ネットワーク上の Pod が MAC アドレスを共有します。これは、セキュリティ制限（VPC ネットワーク）によりポートあたりの MAC アドレス数や未知の MAC アドレスが制限されている場合に使用されます。
* **macvlan** - ネットワーク上の各 Pod が独自の MAC アドレスを持ち、従来のネットワーク接続に準拠します。
* **SR-IOV** - 単一ルート I/O 仮想化は、単一の物理デバイスを複数の Pod で共有するために使用されますが、この機能をサポートするホストデバイスが必要です。

OpenShift（および Kubernetes）では、Multus は NetworkAttachmentDefinition という名前のカスタムリソースタイプを使用します。これは、特定のプロジェクト/ネームスペースに対してサポートされているプラグインのいずれかを使用してネットワークを定義するために使用されます。

あるいは、OpenShift（Kubernetes ではない）では `cluster` Network リソースを編集して `spec.additionalNetworks[]` を定義することもでき、
これにより、目的のプロジェクト/ネームスペースに NetworkAttachmentDefinition が自動的に作成されます。
これは、クラスター全体で NetworkAttachmentDefinition を一元管理するためのポイントとして便利です。

=== NMState Operator [[nmstate_operator]]

NMState ("NM" は NetworkManager の略。RHEL、Fedora、およびその他の Linux ディストリビューション用のネットワーク設定ツール) は、Linux ホスト上のネットワーク設定を管理するために使用される宣言型 API です。

NMState Operator は、独自の API (NodeNetworkConfigurationPolicy) を公開する Kubernetes Operator です。これは NMState を使用して、デプロイ先の Kubernetes (または OpenShift) クラスター内のノードホストのネットワーキングを構成します。

一部の Multus ネットワーク設定（`linux-bridge` など）では、Pod（または VM）が実行される予定のノード上にブリッジインターフェースを作成するために、実際に NMState Operator の使用が必要になる場合があります。

Multus で (NetworkAttachmentDefinition を使用して) ノードホスト上に存在しない可能性のあるインターフェースを使用するネットワークを定義することは可能です。
このようなネットワークに Pod や VM を接続すると、その Pod/VM が実行されるノード上にインターフェースが存在しない限り、失敗します。

== ストレージ API [[storage_apis]]

このセクションでは、OpenShift Virtualization におけるストレージ関連オブジェクトの要点を説明します。以下の各サブセクションは、その特定リソースの Kubernetes `Kind` に従ってタイトルが付けられています。

直接操作することはありませんが、簡単に言及しておくべき API オブジェクトがいくつかあります。

* **VolumeSnapshotContents** - 基盤となるストレージシステム内の実際の「オンディスク」スナップショットオブジェクトを表します。
* **VirtualMachineSnapshotContents** - <<volume_snapshots,VolumeSnapshot>> を作成するために使用されるソース VM、<<persistent_volume_claims,PVCs>>、VolumeSnapshots への参照が含まれています。
* **VolumeSnapshotClasses** - <<storage_classes,StorageClasses>> と同様に、VolumeSnapshotClasses は CSI ドライバーを使用して、特定のストレージプラットフォームの VolumeSnapshot 作成を容易にします。

次のセクションでは、概念が重複しているように見える（ボリューム、スナップショット、データソースなど）いくつかの異なるオブジェクトについて説明します。
その理由は、OpenShift Virtualization が低レベルの Kubernetes ネイティブなリソースの高レベルな抽象化を使用しているためです。

これは、低レベルのリソースを直接扱うのではなく、API レベルでのストレージタスク（クローニング、スナップショット、復元など）を簡素化するためです。
これにより、高レベルのリソースを仮想化のユースケースにより適したものに調整することも可能になります。

=== PersistentVolumes [[persistent_volumes]]

PersistentVolume (PV) は、マウント可能なストレージボリュームを表す Kubernetes ネイティブなリソースであり、<<persistent_volume_claims,PersistentVolumeClaim>> (PVC) を使用して任意の Pod にバインドできます。
PersistentVolume には、それが表すボリュームのサイズ、アクセスモード（ReadWriteOnce、ReadWriteMany など）、リサイクルポリシー、および権限が定義されています。

=== PersistentVolumeClaims [[persistent_volume_claims]]

PersistentVolumeClaim (PVC) は、Pod 用の PersistentVolume にバインドするか、それを要求するために使用されます。これも Kubernetes の主要なリソースであり、
Kubernetes のコンテナワークロードで PersistentVolume を実際に使用するための手段です。PVC は 1:1 マッピングで単一の PV にバインドされ、
その PV がバインドされると（PV で `ReadWriteMany` モードが有効になっていない限り）、解放されてリサイクルまたはガベージコレクションされるまで、他の PVC によって要求または使用されることはありません。

OpenShift と Kubernetes の初期の頃は、ホスト（または SAN / NAS）ストレージレベルで PersistentVolumes を手動でプロビジョニングし、
ストレージホスト上でプロビジョニングされた各ボリュームに対してクラスター上で PersistentVolumes を作成する必要がありました。
しかし、<<storage_classes,StorageClasses>> という新しいリソースのおかげで、ほとんどのクラウドプラットフォームやストレージプロバイダーで PersistentVolumes のプロビジョニングとガベージコレクションが自動化されています。

OpenShift Virtualization では、<<data_sources,DataSources>> と <<data_volumes,DataVolumes>> を使用して kube-ネイティブな PV および PVC を抽象化しており、
それらが VirtualMachines で使用される主要なストレージリソースとなっています。

StorageClasses に依存して空のボリュームをプロビジョニングすることに加えて、PersistentVolumeClaim オブジェクトの `dataSource` フィールドを使用することで、（後述の）VolumeSnapshot からデータを事前入力した PVC を作成できます。
既存の PVC を `dataSource` としてリストした新しい PVC を作成することで、PVC のクローン作成も可能です。

=== VolumeSnapshots [[volume_snapshots]]

VolumeSnapshots は PersistentVolume 状態の特定の時点でのコピーであり、VM ディスクイメージのクローン作成や、PersistentVolume を以前の状態に復元するために使用できます。

VolumeSnapshots は、VirtualMachine の状態を保存するために（後述の）VirtualMachineSnapshots によって使用される低レベルのオブジェクトですが、
KubeVirt DataVolume や DataSource をバックアップする PersistentVolume 状態を保存するために手動で作成することもできます。

=== StorageClasses [[storage_classes]]

StorageClass は、PersistentVolumeClaim が作成されるたびに PersistentVolumes の自動プロビジョニングを提供するために OpenShift および Kubernetes で使用されます。

StorageClasses は CSI ドライバーを使用して、OpenShift 上でベンダーのストレージプラットフォームの実装を提供し、特定のプラットフォーム上で新しいボリューム（Amazon Elastic Block Store など）をプロビジョニングするために使用されるベンダー固有の API を抽象化するため、kube-ネイティブな API (PV および PVC) を使用してそれらを利用できるようになります。

StorageClasses は、プロビジョニング、ガベージコレクション、リサイクルに関するベンダー固有の設定を調整したり、機能を拡張するために OpenShift Virtualization にサポートされていないクラウドやストレージプラットフォームを追加したりする場合を除き、OpenShift Virtualization のユーザーや管理者が直接対話するポイントではありません。

=== DataVolumes [[data_volumes]]

DataVolumes は PersistentVolumeClaims の抽象化を提供し、サポートされているデータソースからの自動プロビジョニングとデータ入力を行います。

DataVolumes がないと、ディスクとして VM に接続する前に、イメージデータを含む PVC を手動で作成して入力する必要があります。
DataVolumes は、基盤となる PVC へのデータのインポートという実際のタスクを処理するために Containerized Data Importer (CDI) に依存しています。

DataVolumes (より具体的には CDI) は、2 つの異なるイメージタイプ (qcow2 および raw) と、PVC に入力するための多数のデータ取り込み手段をサポートしており、
後者のメソッドは 3 つの主なユースケースのいずれかに該当します。

* クライアントマシンからのアップロード
* 外部ソース（Web サーバー、オブジェクトストレージプロバイダー、またはコンテナレジストリ）からのダウンロード
* 既存のソースからのクローン作成（以前に入力された PVC、スナップショットなど）

CDI（および DataVolumes）でサポートされているデータ取り込みメソッドの完全なリストは以下の通りです。

* **blank** - 空のボリュームをプロビジョニング
* **gcs** - GCS エンドポイントからイメージをダウンロード
* **http** - HTTP/S URL からイメージをダウンロード
* **imageio** - ovirt-imageio からイメージをダウンロード
* **pvc** - 既存の PersistentVolumeClaim を使用して新しいボリュームを作成
* **registry** - コンテナイメージレジストリをイメージダウンロードソースとして使用
* **s3** - AWS または互換性のある S3 (MinIO) エンドポイントからイメージをダウンロード
* **snapshot** - 既存の VolumeSnapshot を使用して新しいボリュームを作成
* **upload** - クライアントマシンからイメージをアップロード
* **vddk** - VMware イメージソースを使用

=== DataSources [[data_sources]]

DataSources は「ブート可能なイメージ」と考えることができ、新しい DataVolume をプロビジョニングするために使用される既存の PersistentVolumeClaim または VolumeSnapshot を指すだけです。
OpenShift Virtualization Web コンソールからは、DataSource のみを選択してルートディスクイメージにでき、そこでは「Bootable Volumes」とラベル付けされています。

DataSource `spec` 内でサポートされているフィールドは 1 つだけです。

* **source** - `pvc` または `snapshot` フィールドのみをサポート（これらは相互排他）
** **pvc** または **snapshot** - データソースが PersistentVolumeClaim か VolumeSnapshot かに応じて、ここにある適切なサブフィールドを使用
*** **name** - pvc または snapshot の名前
*** **namespace** - pvc または snapshot が存在するネームスペース

=== VirtualMachineSnapshots [[virtual_machine_snapshots]]

VirtualMachineSnapshot は、特定の VM に接続されているすべてのディスク/ボリュームの状態の特定の時点でのコピーです。

VirtualMachineSnapshot が作成されると、接続されている各ディスクに対して個別の VolumeSnapshot が目的のネームスペースに作成され、
スナップショット処理が完了すると VirtualMachineSnapshot オブジェクトは最終的に完了した Status で更新されます。

VirtualMachineSnapshot オブジェクトは `source` VM 参照を受け入れ、オプションで `1m`、`3600s`、`1h30m` などの時間単位サフィックスや `-1h` などの符号付き値を持つ `failureDeadline` を受け入れます。
デフォルトの期限値は `5m` です。

=== VirtualMachineRestores [[virtual_machine_restores]]

スナップショットの作成は、そのスナップショットを復元する機能（スナップショットが撮影された時点に「時間を巻き戻す」）が存在する場合にのみ役立ちます。
そのため、VM スナップショットから復元する必要が生じたときに VirtualMachineRestore オブジェクトが作成されます。

VirtualMachineRestore は、作成する目的の VM の `apiGroup`、`kind`、`name` を含む `target` VM 参照を受け入れ、復元のソースとして使用する `virtualMachineSnapshotName` を受け入れます。

== クローン API [[clone_api]]

VM のクローンを作成する方法は 3 つあります。最も難しい方法から最も簡単な方法の順にリストします。

* ソース VM から個々の PVC のスナップショットを取得し（VolumeSnapshots を介して）、VM 名やディスク名などの参照を置き換えて VirtualMachine オブジェクトをコピーする。
* VirtualMachineSnapshot を作成する（ボリュームスナップショットは自動作成されますが、VirtualMachine オブジェクトをコピーし、VM/ディスク名、MAC アドレスなどを置き換える必要がある）。
* クローン API を活用して、ソースとターゲットの VirtualMachine（または VirtualMachineSnapshot）名を定義する VirtualMachineClone オブジェクトを作成するだけで、すべてのステップを実行する。

VirtualMachine のクローニングは、<<virtual_machine_clones,VirtualMachineClones>> オブジェクトを作成することによって実行されます。

=== VirtualMachineClones [[virtual_machine_clones]]

スナップショットおよび復元 API をベースにした VirtualMachineClone は、VirtualMachine のスナップショットプロセスと、スナップショットから VM のコピーを復元するプロセスを簡素化するように設計された高レベルの操作です
（特に VM に複数のディスクが接続されている場合）。

クローニングにはスナップショットと復元操作の両方が含まれるため、VirtualMachineClone オブジェクトには `source` と（オプションで）`target` の VirtualMachine 参照の両方が含まれ、各フィールドには目的のソースまたはターゲット VM オブジェクトの `apiGroup`、`kind`、`name` が含まれます。

=== クローン VM の変更 [[mutating_vm_clones]]

VM またはテンプレートのメタデータ (`labels` および/または `annotations`)、MAC アドレス、BIOS / UEFI シリアル番号、あるいはターゲット VM の CPU や RAM スペックなどの詳細など、VM クローンの詳細を変更する必要がある場合があります。

そのような変更に使用されるオブジェクトフィールドを以下に示します（すべてのフィールドは「オプション」です）。

* **labelFilters** - ソース VM からどのラベル (`metadata.labels` から) をクローン VM にコピーするか、またはコピー「しない」かを定義するために使用されます
* **annotationFilters** - ソース VM からどの注釈 (`metadata.annotations` から) を VM クローンにコピーするか、またはコピー「しない」かを定義するために使用されます
* **template** - VM / VMI `template` のメタデータフィルターを定義するために使用され、トップレベルと同じ 2 つのフィルターをサポートします。
** **labelFilters** - ソース VM の `template.metadata.labels` からクローン VM に指定のラベルをコピーまたは除外するために使用されます
** **annotationFilters** - ソース VM の `template.metadata.annotations` からクローン VM に指定の注釈をコピー/除外するために使用されます
* **newMacAddresses** - クローン VM の名前付き `interface` ごとに新しい MAC アドレスを明示的に定義します。このフィールドには、`<interface-name>` キーからハイフンで区切られた文字列 (`00-01-ff-00-01-00`) MAC アドレス値への 1 対 1 のマップが含まれます。
* **newSMBiosSerial** - 新しい SMBios シリアル番号を文字列値として受け入れます
* **patches** (v4.20+) - 上記のオプションではサポートされていないクローン VM の他のフィールドを変更するために使用できる、文字列化された json パッチコマンドのリストを受け入れます。

[NOTE]
====
* すべてのフィルターフィールドは、ワイルドカード (`label-or-annotation-name/*`) と否定 (`!label-or-annotation-name`) の両方を（それぞれ）含める、または除外するためにサポートしており、単一のフィルター文字列に結合できます。
* デフォルトでは、VM のクローン作成時にすべての MAC アドレスが削除されます。
====

上記以外の変更については、`patches` フィールドも受け入れられます。これは、`op`、フィールド `path`、`value` をそれぞれ含む文字列リテラルとして json パッチ（json マージパッチ「ではない」）のリストを受け入れます。

以下は、言及された各フィールドを含む VirtualMachineClone spec の短い例です。

[source,yaml]
----
apiVersion: clone.kubevirt.io/v1beta1
kind: VirtualMachineClone
metadata:
  name: example-vm-clone
  namespace: my-namespace
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: my-virtual-app
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: my-clone-app
  labelFilters:
  - "metadata-labels-to-include/*"
  - "!metadata-labels-to-omit/*"
  annotationFilters:
  - "metadata-annotations-to-include/*"
  - "!metadata-annotations-to-omit/*"
  template:
    labelFilters:
    - "template-labels-to-include/*"
    - "!template-labels-to-omit/*"
    annotationFilters:
    - "template-annotations-to-include/*"
    - "!template-annotations-to-omit/*"
  newMacAddresses:
    nameOfInterface: "ff-00-00-bb-aa-aa"
  newSMBiosSerial: "S3R14LNUM83R"
  patches:
  - '{"op": "add", "path": "/metadata/labels/my-app", "value": "cloned"}'
  - '{"op": "replace", "path": "/spec/instanceType/name", "value": "u1.xlarge"}'
----

=== クローン VM のパッチ適用 [[patching_vm_clones]]

VirtualMachine マニフェストに存在しないフィールド値を追加しており、そのフィールドに存在しない親オブジェクトもある場合は、欠落しているフィールド値を設定する前に空の親オブジェクトを追加する必要があります。

例えば、親オブジェクトは空の値 `{}` を持つ `add` コマンドを使用してパッチを適用する必要があります。

[source,yaml]
----
apiVersion: clone.kubevirt.io/v1beta1
kind: VirtualMachineClone
metadata:
  name: missing-parent-patch-example
  namespace: my-namespace
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: example-source-vm
  patches:
  - '{ "op": "add", "path": "/spec/template/spec/domain/cpu", "value": {} }'
  - '{ "op": "add", "path": "/spec/template/spec/domain/cpu/cores", "value": 6 }'
----

[IMPORTANT]
====
* VirtualMachine で `cpu` または `memory` フィールドを手動で設定すると、`spec.instancetype` フィールドと競合します。
* `spec.instancetype` を削除すると、VM が UI に表示されなくなります。
* CPU とメモリの使用量を構成するには <<instance_types,InstanceTypes>> のセクションを、CPU トポロジーを変更するには <<virtual_machine_preferences,VirtualMachine[Cluster]Preferences>> を参照してください。
* `spec.instancetype` が設定されている VM で `cpu` または `memory` 値にパッチを適用しようとすると、VM の復元が完了せず、クローン操作が無期限にハングします。
====

=== クローニング戦略と StorageProfiles [[vm_cloning_strategies]]

OpenShift Virtualization では、cloneStrategy を使用して、特定のストレージタイプ（OpenShift/Kubernetes で StorageClass として定義されます）のクローニング方法を調整できます。
OpenShift Virtualization（具体的には CDI）は、特定の StorageClass（特定の CSI ドライバーを公開します）の推奨設定を StorageProfile に保存します。
StorageProfile は、そのストレージプロバイダーに最適化された設定でクラスター上の各 StorageClass に対して作成されます。

NOTE: CDI が認識しないストレージプロバイダーの場合、その StorageClass に対して StorageProfile を構成する必要があります。そうしないと、その StorageClass を使用して DataVolumes が定義されるたびに PVC がプロビジョニングされません。

デフォルトでは、OpenShift Virtualization で VirtualMachine のクローンを作成すると、VM のスナップショットが（VolumeSnapshot を作成することによって）取得され、新しい PVC と関連する DataVolumes が作成されてスナップショットが復元されます。

クローニングプロセスが即座に完了しないことに気づくかもしれませんが、これはクローニング（スナップショット/復元）プロセスそのものよりも、CSI ドライバーのブロックレイヤー実装に関係しています。
一部の仮想化プラットフォーム（および OpenShift/Kubernetes 用のいくつかの CSI ドライバー）は、ブロックレベルでのハードリンクや CoW (Copy on Write) 実装により、スナップショットからのインスタントクローニングをサポートしています。

例えば、AWS EBS ボリュームは高速スナップショット復元をサポートしていませんが（link:https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/869[この GitHub イシューを参照,window=_blank]）、オンプレミスのソリューションの中にはサポートしているものがあるかもしれません。

そうは言っても、StorageProfile の cloneStrategy を調整するためのオプションがいくつかあります。

* **snapshot** (デフォルト) - ストレージプロバイダーが認識されており、CSI スナップショットもサポートしている場合（その CSI ドライバー用の VolumeSnapshotClass が存在する場合）、CDI はスナップショットメソッドを使用します。
* **copy** - ソースボリュームからターゲットボリュームへデータをコピーするためにソース Pod とターゲット Pod の両方を使用するフォールバックオプションです。これは最も効率の悪いクローニング方法です。
* **csi-clone** - スナップショットを最初に作成せずに既存のボリュームをクローンするために CSI クローン API を使用します。これは最も効率的な方法ですが、特定の StorageClass 用に StorageProfile で手動指定する必要があります。

`cloneStrategy` を `csi-clone` に設定した StorageProfile オブジェクトの例：

[source,yaml]
----
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: example-provisioner
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteOnce
    volumeMode: Filesystem
  cloneStrategy: csi-clone
----

== エクスポート API [[export_api]]

OpenShift Virtualization は、異なるクラスターや別の仮想化プラットフォームへ移行する場合など、VM やディスクイメージをクラスター外に保存または移動するために使用できるエクスポート API をサポートしています。

VM ディスクイメージは OS、アプリケーション、データを含んでおり、サイズが非常に大きくなる可能性があるため、エクスポートの主要な懸念事項です。
OpenShift API サーバーに過負荷をかけずにクラスター外へのイメージ転送をサポートするために、プロキシサーバーが利用されます。これは、接続された Ingress、Route、または NodePort を持つサービスを使用してインターネットに公開する必要があります。

NOTE: Ingress や Route を使用する代わりに `virtctl port-forward` を使用してエクスポートプロキシサーバーに接続することもできます。

=== エクスポートトークン [[export_tokens]]

VM ディスクにアクセスするユーザーを認証するために（VM 自体と同じネームスペース内の）エクスポートトークンを作成する必要があります。
これは、トークン文字列を保存する K8s シークレットを作成することで行われます。トークンは、エクスポートプロキシエンドポイントにアクセスする際にヘッダー (`x-kubevirt-export-token`) として渡されます。

NOTE: 推奨されるトークン文字列は、長さが 12 文字以上の英数字の値です。

エクスポートトークンの例を以下に示します。

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: export-token
stringData:
  token: abc098765421def
----

トークンシークレットは、VM をエクスポートするために使用される（後述の）VirtualMachineExport オブジェクトから参照されます。

=== VirtualMachineExports [[virtual_machine_exports]]

VirtualMachineExport オブジェクトを作成することで、任意の VirtualMachine、VirtualMachineSnapshot、または PersistentVolumeClaim をエクスポートできます。

エクスポートトークンシークレットの名前を含む `tokenSecretRef` を定義し、上記の `source` タイプのいずれかを定義する必要があります。

VirtualMachine をエクスポートすると VM の yaml マニフェストに加え、VM に関連付けられている PVC、DataVolumes、または MemoryDump ボリュームがエクスポートされますが、VirtualMachineSnapshot や PVC をエクスポートしても VM マニフェストは提供されません。

エクスポートされたアーティファクトには、VirtualMachineExport の `status` ブロックを表示し、提供された URL を使用して準備ができ次第エクスポートされた VM イメージ、ファイル、またはアーカイブをダウンロードすることでアクセスできます。

ダウンロード用に 4 つのフォーマットが提供されています。

* **raw** - ビット単位の qcow2 ディスクイメージ
* **gzip** - gzip 圧縮されたディスクイメージ
* **dir** - PVC 内で検出されたファイルを検索するためのディレクトリリストを提供します。特定のファイルにアクセスするには、URL 内の `/dir` を `/path/to/file.txt` に置き換えます
* **tar.gz** - 単一の gzip 圧縮された tar アーカイブとしての PVC の全内容

コンテンツタイプによって、エクスポートに使用されるフォーマットが決定されます。

* **KubeVirt content-type** - PVC が KubeVirt ディスクとして検出された場合、`raw` および `gzip` フォーマットが使用されます
* **Archive content-type** - それ以外の場合、PVC に KubeVirt ディスクが「含まれていない」なら `dir` および `tar.gz` フォーマットが使用されます

VirtualMachineExport の例を以下に示します。

[source,yaml]
----
apiVersion: export.kubevirt.io/v1beta1
kind: VirtualMachineExport
metadata:
  name: export-example <1>
spec:
  tokenSecretRef: export-token <2>
  source: <3>
    apiGroup: "kubevirt.io"
    kind: VirtualMachine
    name: virtual-machine-example
----
<1> 定義されている VirtualMachineExport オブジェクトの名前
<2> エクスポートトークンを含むシークレットの名前
<3> ソースは、特定のグループ/バージョンおよび kind への名前付き参照

サポートされているソースタイプは以下の通りです。

[cols="1,1"]
|===
| apiGroup |kind

|kubevirt.io
|VirtualMachine

|snapshot.kubevirt.io
|VirtualMachineSnapshot

|""
|PersistentVolumeClaim
|===