= 仮想マシン用 Linux bridge セカンダリーネットワークの作成
:navtitle: Linux bridge

テスト済みバージョン:
----
OpenShift 4.20,4.21
----

Linux bridge セカンダリーネットワークは、 https://nmstate.io/kubernetes-nmstate/[Kubernetes NMState Operator,_window=blank]を使用してクラスターノード上に新しい Linux bridge デバイスを作成し、 https://github.com/k8snetworkplumbingwg/multus-cni[Multus CNI,window=_blank]を https://www.cni.dev/plugins/current/main/bridge/[bridge CNI プラグイン,_window=blank]と組み合わせて、Pod および `VirtualMachine` (VM) をブリッジに接続します。

この Linux bridge はノードのネットワーク namespace で実行され、同じノード上で実行されている Pod や VM 間のレイヤー 2 ネットワークスイッチとして機能します。
また、Linux bridge を物理ホストインターフェースにリンクすることで、クラスター内の他のノードで実行されている VM や Pod への接続を含め、外部ネットワークへの接続を可能にすることもできます。

要約すると、以下の条件が適用される場合に Linux bridge セカンダリーネットワークを使用できます。

* プライマリネットワークとして使用する予定がない場合 (現在、OpenShift で bridge CNI プラグインを使用してこれを行うことはできません) 
* VM をクラスター外部のネットワーク (または NAT ゲートウェイを介さずにローカル/物理ネットワーク) に接続する必要がある場合
* `VirtualMachine` を VLAN に接続する必要がある場合

NOTE: Linux bridge の `NetworkAttachmentDefinition` は、`VirtualMachine` を VLAN に接続するための最も簡単な方法です。

== 前提条件

* OpenShift Virtualization Operator がインストールされた OpenShift 4.20 以降のクラスター
* クラスターに NMState Operator がインストールされていること
* NodeNetworkConfigurationPolicy および NetworkAttachmentDefinition リソースを作成するためのクラスター管理者アクセス権限
* インストール済みの CLI ツール: `oc`, `virtctl`
* Worker Node で利用可能な物理ネットワークインターフェース (外部ネットワークに接続する場合)

== 手順

プロセスは以下の手順に分けられます。

* <<create_linux_bridge_nncp,Linux bridge ノードネットワーク設定ポリシーの作成>>
* <<create_net_attach_def,NetworkAttachmentDefinition の作成>> (ブリッジネットワークを Pod および VM に公開) 
* <<attach_virtual_machines,VirtualMachine の接続>> (Linux bridge セカンダリーネットワークへ VM を接続) 
** <<create_first_vm,最初の VirtualMachine の作成>>
** <<create_second_vm,2 つ目の VirtualMachine の作成>>
* <<test_secondary_network,Linux bridge セカンダリーネットワークのテスト>>

== Linux bridge Node Network Configuration Policy の作成 [[create_linux_bridge_nncp]]

最初のステップは、`NodeNetworkConfigurationPolicy` (`nncp`) を使用してクラスターノード上に Linux bridge を定義することです。
すべての `nncp` オブジェクトはクラスタースコープであるため、namespace には存在しません。
ただし、キーと値のラベルを使用して、`nncp` を適用するノードを制御することは可能です。


[IMPORTANT]
====
.必要な手順:
* `NodeNetworkConfigurationPolicy` を作成するには、Kubernetes NMState Operator をインストールしておく必要があります。
* `nncp` の作成をスキップしてセカンダリーブリッジアダプターで VM を起動しようとすると、起動に失敗します。
====

以下の `NodeNetworkConfigurationPolicy` をコピーし、`lnbr0-bridge.nncp.yaml` という名前の新しいファイルに貼り付けます。
外部ネットワークに接続するには、最後の 2 行のコメントを外し、ノード上の 2 つ目、または 3 つ目 (プライマリとセカンダリーがボンディングされている場合) のデバイス名と一致するようにデバイス名を変更する必要があります。

[source,yaml]
----
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: lnbr0-bridge
spec:
  desiredState:
    interfaces:
    - name: lnbr0
      description: layer2-only linux bridge with an optional port
      type: linux-bridge
      state: up
      ipv4:
        enabled: false
      bridge:
        options:
          stp:
            enabled: false
        # Uncomment below and change the interface name
        # to match the desired physical host port
        #port:
        #- name: ens1
----

.上記の例について:
* *`lnbr0`* (`linux bridge 0` の短縮形): この例における Linux bridge のインターフェース名です。名前は任意です。
* *`ipv4`*: ブリッジ自体がゲートウェイとして機能する場合を除き、独自の IP アドレスを必要としないため、IP アドレス割り当ては無効になっています。
* *`options.stp.enabled`*: スパニングツリープロトコルを有効または無効にするブール値です (この例では無効) 。
* *`port`* (コメントアウト): ブリッジインターフェースをバインドするネットワークアダプターのリスト (通常は 1 つのみ) です。
** *`name`*: (コメントアウト) ブリッジをバインドする物理ホストデバイスの名前です。コメントアウトされた例では `ens1` を使用しましたが、環境によって異なる場合があります。

NOTE: フィールドの説明と例を含む完全なスキーマについては、 https://nmstate.io/devel/yaml_api.html[NMState API ガイド,window=_blank]を参照してください。

ファイルを `lnbr0-bridge.nncp.yaml` として保存したら、`nncp` マニフェストを OpenShift クラスターに適用します。

[source,bash,role=execute]
----
oc create -f lnbr0-bridge.nncp.yaml
----

数分後、クラスター内の各該当ノードで、設定された接続状態を持つ `lnbr0` という名前の新しいブリッジインターフェースが作成されます。

この進行状況を確認するには、`NodeNetworkConfigurationPolicy` に関連するアクションを実行する `NodeNetworkConfigurationEnactment` (`nnce`) オブジェクトを表示します。

[source,bash,role=execute]
----
oc get nnce
----

上記のコマンドを実行すると、適用が完了するまでクラスター内の各ノードのステータスが `Progressing` となり、その後各ノードのステータスが `Available` に変わります。

`lnbr0` インターフェースがノード上に存在することを確認するには、クラスターの `NodeNetworkState` を表示する (各ノードで `ip addr show` を実行するのと同等) 、またはノードでデバッグセッションを開始します。

クラスター内のすべてのノードの `NodeNetworkState` を表示するには、`nns` リソースを取得し、必要に応じてブリッジインターフェースを `grep` します。

[source,bash,role=execute]
----
oc describe nns | grep lnbr0
----

NOTE: `nmstate` オブジェクト (NMState Operator をトリガーするもの) と同様に、`nncp` オブジェクトもクラスタースコープであるため、namespace は不要です。ただし、クラスター内に複数の `nncp` オブジェクトを共存させることは可能です。

ノード上に Linux bridge インターフェースが存在することが確認できたら、<<create_net_attach_def,NetworkAttachmentDefinition の作成>>に進みます。


== Linux bridge NetworkAttachmentDefinition の作成 [[create_net_attach_def]]
次のステップは、Pod/VM に L2 ネットワーキングを提供する `NetworkAttachmentDefinition` を作成することです。
`NetworkAttachmentDefinition` は、特定のプロジェクト/namespace 内の Pod/VM がセカンダリーネットワークに接続できるようにするためのものです。

IMPORTANT: `NetworkAttachmentDefinition` を作成するために必須ではありませんが、`VirtualMachine` をブリッジネットワークに接続する前に、ブリッジインターフェースを定義する `nncp` オブジェクトがクラスター内に存在している必要があります。
これを怠ると、ブリッジベースの NIC を持つ VM は起動できなくなります。

まず、VM 用の namespace が存在しない場合は作成します。

[source,bash,role=execute]
----
oc create namespace bridge-demo
----

次に、その namespace に切り替えます。

[source,bash,role=execute]
----
oc project bridge-demo
----

続いて、以下の `NetworkAttachmentDefinition` をコピーし、`lnbr0-bridge.net-attach-def.yaml` という新しいファイルに貼り付けます。
`nncp` で物理ポートをバインドすることを選択した場合は、必要に応じて `vlan` ID を変更してください。

[source,yaml]
----
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lnbr0-bridge
  namespace: bridge-demo
spec:
  config: '{
    "name": "lnbr0-bridge",
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "lnbr0",
    "ipam": {},
    "vlan": 1,
    "macspoofchk": false,
    "disableContainerInterface": false,
    "portIsolation": false
  }'
----

上記の例の各フィールドについて説明します (オプションのフィールドはそれぞれのデフォルト値で表示されています) 。

* *`metadata.name`*: `NetworkAttachmentDefinition` の Kubernetes 名です。
* *`metadata.namespace`*: Pod/VM が実行されている namespace (この例では `bridge-demo`) と一致させる必要がありますが、別の namespace に存在することも可能です。
* *`spec.config`*: 以下のサブフィールドを持つ JSON 文字列値を受け入れます。
** *`"name"`*: 設定の名前。`metadata.name` と一致させるのが理想的です。
** *`"cniVersion"`*: 現在サポートされている CNI バージョンは `"0.3.1"` のみです。
** *`"type"`* (必須): Linux bridge インターフェースを使用するには `"bridge"` に設定する必要があります。
** *`"bridge"`* (必須): NNCP 定義を介してノード/ホスト上で定義されたブリッジインターフェースの名前。
** *`"ipam"`* (非サポート): OpenShift Virtualization は bridge CNI プラグインを使用した IP アドレス管理をサポートしていないため、このフィールドは空にする必要があります (`layer2` 専用) 。
** *`"vlan"`* (オプション): インターフェースで利用したい VLAN ID (デフォルトは `1`) 。
** *`"macspoofchk"`* (オプション): MAC スプーフィングチェックを有効にするかどうか。コンテナから送信されるトラフィックをインターフェースの MAC アドレスに制限します (デフォルトは `false`) 。
** *`"disableContainerInterface"`* (オプション): コンテナネットワークインターフェース (veth peer) の状態をダウンに設定します (デフォルトは `false`) 。
** *`"portIsolation"`* (オプション): ホストインターフェースで Isolation を設定するための設定。これによりコンテナ間の通信が防止され、ホストとの通信またはゲートウェイ経由の通信のみが強制されます (デフォルトは `false`) 。

Linux bridge CNI プラグインのその他の構成例 (OpenShift Virtualization ではサポートされていない例を含む) については、 https://www.cni.dev/plugins/current/main/bridge/[bridge CNI プラグインのドキュメント,window=_blank]、および公式の https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/virtualization/networking#virt-creating-linux-bridge-nad-cli_virt-connecting-vm-to-linux-bridge[OpenShift ドキュメント,window=_blank]を参照してください。

[NOTE]
====
.IP アドレス割り当てとインターフェースボンディング:
* 前述の通り、`VirtualMachine` の `NetworkAttachmentDefinition` での IP アドレス管理 (IPAM) の使用は OpenShift Virtualization ではサポートされていないため、`"ipam": {}` 定義は空のままにする必要があります。
* Linux bridge ネットワーク上の VM インターフェースに IP アドレスを割り当てるには、次のいずれかの方法を使用します。
** *cloud-init networkData*: VM の cloud-init 設定で静的 IP アドレスを設定 (予測可能な IP アドレス割り当てで推奨) 
** *外部 DHCP サーバー*: ブリッジネットワーク上に DHCP サーバーが存在する場合、VM は自動的に IP アドレスを取得
** *手動設定*: 起動後、VM 内部で `nmcli` やネットワーク設定を使用して手動で IP アドレスを設定
* OpenShift Virtualization は、 https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html/configuring_and_managing_networking/configuring-a-network-bond#upstream-switch-configuration-depending-on-the-bonding-modes[Linux bridge bonding mode,window=_blank] 0、5、6 をサポートしていません。
====

ファイルを `lnbr0-bridge.net-attach-def.yaml` として保存したら、`network-attachment-definition` を OpenShift クラスターに適用します。

[source,bash,role=execute]
----
oc create -f lnbr0-bridge.net-attach-def.yaml
----

`network-attachment-definition` が正常に作成されたことを確認します。

[source,bash,role=execute]
----
oc get net-attach-def lnbr0-bridge
----

3 つのコンポーネントのうち 2 つが揃ったので、最後のコンポーネントである <<attach_virtual_machines,VirtualMachine の接続>> に進みます。

== VirtualMachine のセカンダリーネットワークへの接続 [[attach_virtual_machines]]

このステップでは、ブリッジにセカンダリーネットワークとして接続される 2 つの新しい VirtualMachine を作成します。

これまでの作業をまとめると、以下の通りです。

* `kubernetes-nmstate-operator` をインストールし、`nmstate` オブジェクトを作成してデプロイをトリガーしました (本ガイドより前のチュートリアル) 。
* `NodeNetworkConfigurationPolicy` を適用し、OpenShift クラスターノード上に Linux bridge デバイスを作成しました。
* 進行中に `NodeNetworkConfigurationEnactment` を表示してブリッジのデプロイを監視しました。
* `NodeNetworkState` オブジェクトを表示して、ノード上にブリッジが存在することを確認しました。
* (Multus) `NetworkAttachmentDefinition` を作成しました。これにより、`VirtualMachine` が Linux bridge に接続し、仮想スイッチとして、または (物理デバイスにバインドされている場合は) ホストネットワークへのブリッジとして機能できるようになります。

以上のポイントを踏まえ、<<create_first_vm,最初の VirtualMachine の作成>> に進みます。

=== 最初の VirtualMachine の作成 [[create_first_vm]]

これまでと同様に、このセクションでは提供された YAML データを使用してオブジェクト (`kind`: `VirtualMachine`) のマニフェストを作成し、`oc apply` を使用してクラスターに適用します。

以下の VirtualMachine マニフェストを使用して、YAML コンテンツを `fedora-bridge-demo.vm.yaml` という名前の新しいファイルにコピーして貼り付けます。

WARNING: この例の cloud-init パスワードはデモ目的専用です。本番環境では常に強力でユニークなパスワードまたは SSH 鍵認証を使用してください。

[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-bridge-demo
  namespace: bridge-demo
  labels:
    app: fedora-bridge-demo
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: fedora-bridge-demo-root
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  instancetype:
    name: u1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: fedora-bridge-demo
    spec:
      domain:
        devices:
          disks:
          - name: fedora-bridge-demo-root
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            name: nic-linux-bridge
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: lnbr0-bridge
        name: nic-linux-bridge
      volumes:
      - name: fedora-bridge-demo-root
        dataVolume:
          name: fedora-bridge-demo-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp2s0:
                addresses:
                - 192.168.50.10/24
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
----

上記の例の特定のフィールドを確認します (すべてのフィールドパスは `spec.template.spec` からの相対パスです) 。

* *`domain.devices.interfaces`*: プライマリの `default` とセカンダリーの `nic-linux-bridge` という 2 つのインターフェースがリストされています。
** *`bridge`*: VM の NIC をホストコンテナに接続する 2 つの方法のうちの 1 つ (もう 1 つは IP `masquerade`)。
これは vm-to-container ブリッジを使用しますが、`lnbr0` ブリッジは container-to-node を接続します (これで接続が完了します) 。
** *`name`*: 後で `network` セクションで参照される任意の識別子
* *`networks`*: `interfaces` が接続されているネットワークのリスト
** *`name`*: `interfaces` フィールドで定義されたブリッジインターフェースの名前
** *`multus.networkName`*: Pod/VM にブリッジネットワークへのアクセスを提供する `NetworkAttachmentDefinition` (NAD) の名前
* *`volumes`*: 2 つの名前付きボリュームがあります。1 つはルートの `datavolumedisk`、もう 1 つは `cloudinitdisk` です。
** *`CloudInitNoCloud`*: これが cloud-init ディスクであり、 https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html[NoCloud,window=_blank]データソースを使用することを KubeVirt に通知します。
*** *`networkData`*: 上記では、セカンダリーインターフェース (`enp2s0`) に静的 IP (`192.168.50.10/24`) が構成されます。
**** *`ethernets`*: セカンダリーインターフェース名 `enp2s0` は、KubeVirt の 2 番目のネットワークインターフェースに対する想定可能な命名規則に従います。

NOTE: プライマリインターフェース (`enp1s0`) は Masquerade を使用し、Pod ネットワークから IP を取得します。

`VirtualMachine` マニフェストを `fedora-bridge-demo.vm.yaml` という名前のファイルとして保存したら、それを OpenShift クラスターに適用します。

[source,bash,role=execute]
----
oc apply -f fedora-bridge-demo.vm.yaml
----

`VirtualMachine` の状態を確認します。VM を起動する前に、基盤となる `DataVolume` のクローン作成に時間がかかります。
VM が `Running` 状態になるのを待つのではなく、2 つ目の VM の作成を進めることができます。

[source,bash,role=execute]
----
oc get vm fedora-bridge-demo
----

== 2 つ目の VirtualMachine の作成 [[create_second_vm]]

次の `VirtualMachine` マニフェストは、最初の `vm` から名前 (ラベルやボリューム名を含む) と IP アドレスを変更していますが、それ以外は同一です。
提供された YAML をコピーし、`fedora-bridge-demo2.vm.yaml` という新しいファイルに貼り付けます。

[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-bridge-demo2
  namespace: bridge-demo
  labels:
    app: fedora-bridge-demo2
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: fedora-bridge-demo2-root
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  instancetype:
    name: u1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: fedora-bridge-demo2
    spec:
      domain:
        devices:
          disks:
          - name: fedora-bridge-demo2-root
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            name: nic-linux-bridge
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: lnbr0-bridge
        name: nic-linux-bridge
      volumes:
      - name: fedora-bridge-demo2-root
        dataVolume:
          name: fedora-bridge-demo2-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp2s0:
                addresses:
                - 192.168.50.20/24
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
----

ファイルを `fedora-bridge-demo2.vm.yaml` として保存したら、この 2 つ目の `VirtualMachine` を OpenShift クラスターに適用します。

[source,bash,role=execute]
----
oc create -f fedora-bridge-demo2.vm.yaml
----

両方の VM が実行されていることを確認し、各 `VirtualMachineInstance` (`vmi`) を直接調べてネットワーク `interfaces` の `status` を確認します。

[source,bash,role=execute]
----
oc get vm -n bridge-demo
oc get vmi fedora-bridge-demo -n bridge-demo -o jsonpath='{.status.interfaces}' | jq .
oc get vmi fedora-bridge-demo2 -n bridge-demo -o jsonpath='{.status.interfaces}' | jq .
----

2 つ目の VM が実行されアクティブになったら、<<test_secondary_network,テスト>> に進みます。


== Linux bridge セカンダリーネットワークのテスト [[test_secondary_network]]

変更されていない例では、Linux bridge セカンダリーネットワークは単純な仮想スイッチとして機能し、(物理ノードインターフェースにブリッジされていない場合は) 同じノード内の Pod、VM、namespace にまたがります。

Linux bridge を介した接続性をテストする最も簡単な方法は、ある `VirtualMachine` から別の `VirtualMachine` への基本的な接続性をテストすることです。

テストを進める前に、`bridge-demo` namespace に以下のリソースが存在している必要があります。

* `NetworkAttachmentDefinition`: `lnbr0-bridge`
* `VirtualMachine`: `fedora-bridge-demo` (セカンダリー NIC IP アドレス: 192.168.50.10)
* `VirtualMachine`: `fedora-bridge-demo2` (セカンダリー NIC IP アドレス: 192.168.50.20)

テストする最も簡単な方法は、一方の VM (または必要に応じて両方の VM) のコンソールに接続し、もう一方に ping を送信することです。

`virtctl` コマンドを使用して最初の VirtualMachine のコンソールにアクセスし、**user**:`fedora`、**password**:`fedora` でログインします (ログインプロンプトが表示されない場合は `ENTER` を押してください) 。

[source,bash,role=execute]
----
virtctl console fedora-bridge-demo
----

VirtualMachine の IP アドレスを確認します。以下のコマンドで、`enp2s0` インターフェースに対して静的アドレス `192.168.50.10` が返されるはずです。

[source,bash]
----
ip addr show
----

最初の VM のコンソールから、`fedora-bridge-demo2` (IP アドレス: `192.168.50.20`) の `VirtualMachine` に ping を送信します。応答が表示されれば、セカンダリーネットワークは動作しています (`CTRL+C` を押すと ping を停止します) 。

[source,bash]
----
ping 192.168.50.20
----

VM コンソールを終了するには、`CTRL+]` を押します。

このチュートリアルのリソースをすべてクリーンアップするには、別の namespace に切り替えて `bridge-demo` namespace を削除します。

[source,bash,role=execute]
----
oc project default
oc delete namespace bridge-demo
----

== まとめ

このチュートリアルでは、以下のことを学びました。

* NMState Operator を使用して `NodeNetworkConfigurationPolicy` でクラスターノード上に Linux bridge を作成する方法
* bridge CNI プラグインを使用して `NetworkAttachmentDefinition` を作成し、ブリッジネットワークを VM に公開する方法
* Primary masquerade インターフェースと Secoudary bridge インターフェースの両方で VirtualMachine を構成する方法
* cloud-init `networkData` を使用してブリッジネットワークに静的 IP アドレスを割り当てる方法
* Linux bridge セカンダリーネットワーク上の VM 間の L2 接続性を確認する方法

== 参照

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/virtualization/networking#virt-connecting-vm-to-linux-bridge_virt-connecting-vm-to-linux-bridge[OpenShift Virtualization - VM の Linux ブリッジへの接続,window=_blank]
* link:https://nmstate.io/devel/yaml_api.html[NMState API ガイド,window=_blank]